#!/bin/bash
# Generate Daily Report - Automated summary for end-of-day
# Usage: ./generate-daily-report.sh

DATE=$(date +%Y-%m-%d)
REPORT_FILE="memory/daily-report-${DATE}.md"

cd /Users/clawdbot/clawd

cat > "$REPORT_FILE" << EOF
# Daily Report - ${DATE}

**Generated:** $(date '+%Y-%m-%d %H:%M:%S')

---

## Stats Snapshot

| Metric | Value |
|--------|-------|
| Total commits | $(git log --oneline | wc -l | tr -d ' ') |
| Today's commits | $(git log --since="midnight" --oneline | wc -l | tr -d ' ') |
| Memory files | $(ls memory/*.md 2>/dev/null | wc -l | tr -d ' ') |
| Songs released | $(ls songs/audio/*.mp3 2>/dev/null | wc -l | tr -d ' ') |
| Workspace size | $(du -sh . | cut -f1) |

---

## Commits Today

$(git log --since="midnight" --pretty=format:"- %s" | head -20)

---

## Files Modified Today

$(git log --since="midnight" --name-only --pretty=format: | sort -u | grep -v "^$" | head -20)

---

## Status

$(git status --short | wc -l | tr -d ' ') working tree changes

---

*Auto-generated by generate-daily-report.sh*
EOF

echo "✅ Daily report generated: $REPORT_FILE"
