name: Auto Commit

on:
  schedule:
    # Run every day at 9 AM
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Make changes
      run: |
        echo "$(date)" >> activity.log
    
    - name: Commit and push
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "chore: auto-update $(date +%Y-%m-%d)" || exit 0
        git push
