#!/usr/bin/env node

/**
 * Changelog Generator
 * Generates CHANGELOG.md from git commits
 * 
 * Usage: changelog-gen [--output CHANGELOG.md]
 * 
 * Price: $20
 */

const { execSync } = require('child_process');
const fs = require('fs');

function getCommits() {
  const log = execSync('git log --pretty=format:"%H|%s|%ad|%an" --date=short', { encoding: 'utf8' });
  return log.trim().split('\n').map(line => {
    const [hash, subject, date, author] = line.split('|');
    return { hash: hash.slice(0, 7), subject, date, author };
  });
}

function categorizeCommit(subject) {
  if (subject.startsWith('feat:') || subject.startsWith('feature:')) return 'Features';
  if (subject.startsWith('fix:') || subject.startsWith('bugfix:')) return 'Bug Fixes';
  if (subject.startsWith('docs:')) return 'Documentation';
  if (subject.startsWith('refactor:')) return 'Refactoring';
  if (subject.startsWith('test:')) return 'Tests';
  if (subject.startsWith('chore:')) return 'Chores';
  return 'Other';
}

function groupByDate(commits) {
  const groups = {};
  commits.forEach(commit => {
    if (!groups[commit.date]) groups[commit.date] = [];
    groups[commit.date].push(commit);
  });
  return groups;
}

function generateChangelog(commits) {
  const grouped = groupByDate(commits);
  const dates = Object.keys(grouped).sort().reverse();
  
  let changelog = `# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

`;

  dates.forEach(date => {
    const dayCommits = grouped[date];
    const categorized = {};
    
    dayCommits.forEach(commit => {
      const category = categorizeCommit(commit.subject);
      if (!categorized[category]) categorized[category] = [];
      categorized[category].push(commit);
    });

    changelog += `## [Unreleased] - ${date}\n\n`;
    
    Object.keys(categorized).sort().forEach(category => {
      if (categorized[category].length > 0) {
        changelog += `### ${category}\n\n`;
        categorized[category].forEach(commit => {
          const message = commit.subject.replace(/^(feat|fix|docs|refactor|test|chore):\s*/, '');
          changelog += `- ${message} ([${commit.hash}])\n`;
        });
        changelog += '\n';
      }
    });
  });

  changelog += `---

*Generated by Claudia's Changelog Generator*  
*Need customization? claudiaclawdbot@gmail.com*
`;

  return changelog;
}

// CLI
const args = process.argv.slice(2);
const outputFile = args.includes('--output') ? args[args.indexOf('--output') + 1] : 'CHANGELOG.md';

console.log('📝 Changelog Generator\n');

try {
  const commits = getCommits();
  console.log(`Found ${commits.length} commits\n`);
  
  const changelog = generateChangelog(commits);
  fs.writeFileSync(outputFile, changelog);
  
  console.log(`✅ Generated ${outputFile}`);
  console.log(`📊 Commits: ${commits.length}`);
  console.log(`📅 Date range: ${commits[commits.length - 1].date} to ${commits[0].date}`);
  console.log('\n📧 Need customization? claudiaclawdbot@gmail.com');
  
} catch (error) {
  console.error('Error:', error.message);
  console.log('\nMake sure you\'re in a git repository.');
}
