#!/usr/bin/env node
/**
 * Claudia Report Generator
 * Unified CLI for all report types
 * 
 * Usage: claudia-report <type> [options]
 * 
 * @module claudia-report
 * @version 1.0.0
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Configuration
const REPO_ROOT = execSync('git rev-parse --show-toplevel', { encoding: 'utf8' }).trim();
const DEFAULT_DATE = new Date().toISOString().split('T')[0];

// Colors for terminal output
const colors = {
  reset: '\x1b[0m',
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m'
};

// Helper functions
const log = {
  info: (msg) => console.log(`${colors.blue}[INFO]${colors.reset} ${msg}`),
  success: (msg) => console.log(`${colors.green}[OK]${colors.reset} ${msg}`),
  warn: (msg) => console.log(`${colors.yellow}[WARN]${colors.reset} ${msg}`),
  error: (msg) => console.error(`${colors.red}[ERROR]${colors.reset} ${msg}`)
};

function exec(cmd, options = {}) {
  try {
    return execSync(cmd, { 
      encoding: 'utf8',
      cwd: REPO_ROOT,
      ...options 
    }).trim();
  } catch (err) {
    return options.default || '';
  }
}

// Report generators
const reports = {
  /**
   * Generate daily standup report
   */
  standup(date = DEFAULT_DATE, options = {}) {
    const { slack = false } = options;
    
    const commits = exec(`git log --oneline --since="${date} 00:00" --until="${date} 23:59"`, { default: 'No commits today' });
    const commitCount = exec(`git rev-list --count HEAD --since="${date} 00:00" --until="${date} 23:59"`, { default: '0' });
    const branch = exec('git branch --show-current', { default: 'N/A' });
    
    let report = slack ? '' : `# 📊 Daily Standup Report - ${date}\n\n`;
    
    if (!slack) {
      report += `**Generated:** ${new Date().toLocaleString()}\n`;
      report += `**Branch:** ${branch}\n\n`;
    }
    
    report += `## 📈 Git Activity\n\n`;
    report += `**Commits today:** ${commitCount}\n\n`;
    
    if (commits !== 'No commits today') {
      report += slack ? '*Commits:*\n' : '### Commits\n\n';
      report += commits.split('\n').map(c => slack ? `• ${c}` : `- ${c}`).join('\n');
      report += '\n\n';
    }
    
    // Get files changed
    try {
      const stats = exec(`git diff --stat HEAD~${commitCount}..HEAD`, { default: '' });
      if (stats && !slack) {
        report += `### Files Changed\n\n\`\`\`\n${stats}\n\`\`\`\n\n`;
      }
    } catch (e) {
      // Ignore
    }
    
    // Summary for Slack
    if (slack) {
      report += `\n*Summary:* ${commitCount} commits today\n`;
    }
    
    return report;
  },

  /**
   * Generate daily report with stats
   */
  daily(date = DEFAULT_DATE, options = {}) {
    const totalCommits = exec('git log --oneline | wc -l', { default: '0' });
    const todayCommits = exec(`git log --since="${date} 00:00" --oneline | wc -l`, { default: '0' });
    const memoryFiles = exec('ls memory/*.md 2>/dev/null | wc -l', { default: '0' });
    const songs = exec('ls songs/audio/*.mp3 2>/dev/null | wc -l', { default: '0' });
    const size = exec('du -sh . | cut -f1', { default: '0B' });
    
    const todayCommitList = exec(`git log --since="${date} 00:00" --pretty=format:"- %s"`, { default: '' });
    const modifiedFiles = exec(`git log --since="${date} 00:00" --name-only --pretty=format: | sort -u | grep -v "^$"`, { default: '' });
    const workingChanges = exec('git status --short | wc -l', { default: '0' });
    
    let report = `# Daily Report - ${date}\n\n`;
    report += `**Generated:** ${new Date().toLocaleString()}\n\n`;
    
    report += `## Stats Snapshot\n\n`;
    report += `| Metric | Value |\n`;
    report += `|--------|-------|\n`;
    report += `| Total commits | ${totalCommits} |\n`;
    report += `| Today's commits | ${todayCommits} |\n`;
    report += `| Memory files | ${memoryFiles} |\n`;
    report += `| Songs released | ${songs} |\n`;
    report += `| Workspace size | ${size} |\n\n`;
    
    if (todayCommitList) {
      report += `## Commits Today\n\n`;
      report += todayCommitList.split('\n').slice(0, 20).join('\n');
      report += '\n\n';
    }
    
    if (modifiedFiles) {
      report += `## Files Modified Today\n\n`;
      report += modifiedFiles.split('\n').slice(0, 20).join('\n');
      report += '\n\n';
    }
    
    report += `## Status\n\n`;
    report += `${workingChanges} working tree changes\n\n`;
    report += `---\n\n*Auto-generated by claudia-report*\n`;
    
    return report;
  },

  /**
   * Generate git activity summary
   */
  gitActivity(since = 'yesterday', options = {}) {
    const sinceArg = since === 'yesterday' ? '1 day ago' : since;
    
    const commits = exec(`git log --oneline --since="${sinceArg}"`, { default: 'No commits' });
    const authors = exec(`git log --since="${sinceArg}" --format="%an" | sort | uniq -c | sort -rn`, { default: '' });
    const filesChanged = exec(`git diff --name-only --since="${sinceArg}" | sort | uniq`, { default: '' });
    
    let report = `# Git Activity Report\n\n`;
    report += `**Period:** Since ${sinceArg}\n`;
    report += `**Generated:** ${new Date().toLocaleString()}\n\n`;
    
    report += `## Commits\n\n`;
    report += commits || 'No commits in this period\n';
    report += '\n\n';
    
    if (authors) {
      report += `## Contributors\n\n`;
      report += authors.split('\n').map(a => `- ${a.trim()}`).join('\n');
      report += '\n\n';
    }
    
    if (filesChanged) {
      report += `## Files Changed\n\n`;
      report += filesChanged.split('\n').slice(0, 30).map(f => `- ${f}`).join('\n');
      report += '\n\n';
    }
    
    return report;
  },

  /**
   * Generate workspace summary
   */
  summary(options = {}) {
    const totalFiles = exec('find . -type f -not -path "./node_modules/*" -not -path "./.git/*" | wc -l', { default: '0' });
    const codeFiles = exec('find . -name "*.js" -o -name "*.ts" -o -name "*.sh" | wc -l', { default: '0' });
    const docs = exec('find . -name "*.md" | wc -l', { default: '0' });
    const size = exec('du -sh . | cut -f1', { default: '0B' });
    const lastCommit = exec('git log -1 --format="%h - %s (%ar)"', { default: 'No commits' });
    
    let report = `# Workspace Summary\n\n`;
    report += `**Generated:** ${new Date().toLocaleString()}\n\n`;
    
    report += `## Overview\n\n`;
    report += `| Metric | Value |\n`;
    report += `|--------|-------|\n`;
    report += `| Total files | ${totalFiles} |\n`;
    report += `| Code files | ${codeFiles} |\n`;
    report += `| Documentation | ${docs} |\n`;
    report += `| Repository size | ${size} |\n\n`;
    
    report += `## Latest Activity\n\n`;
    report += `${lastCommit}\n\n`;
    
    report += `## Directory Structure\n\n`;
    report += '```\n';
    report += exec('tree -L 2 -d | head -30', { default: 'tree not installed' });
    report += '\n```\n\n';
    
    return report;
  }
};

// CLI argument parsing
function parseArgs() {
  const args = process.argv.slice(2);
  const options = {
    type: null,
    date: DEFAULT_DATE,
    output: null,
    format: 'markdown',
    slack: false,
    since: 'yesterday'
  };
  
  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    
    if (!options.type && !arg.startsWith('-')) {
      options.type = arg;
    } else if (arg === '--date' || arg === '-d') {
      options.date = args[++i];
    } else if (arg === '--output' || arg === '-o') {
      options.output = args[++i];
    } else if (arg === '--format' || arg === '-f') {
      options.format = args[++i];
    } else if (arg === '--slack') {
      options.slack = true;
    } else if (arg === '--since') {
      options.since = args[++i];
    } else if (arg === '--help' || arg === '-h') {
      showHelp();
      process.exit(0);
    }
  }
  
  return options;
}

function showHelp() {
  console.log(`
Claudia Report Generator
========================

Usage: claudia-report <type> [options]

Types:
  standup       Generate daily standup report
  daily         Generate daily activity report with stats
  git-activity  Generate git commit summary
  summary       Generate workspace overview

Options:
  --date, -d <date>     Date for report (YYYY-MM-DD)
  --output, -o <file>   Output file (default: stdout)
  --format, -f <fmt>    Output format: markdown, json
  --slack               Slack-formatted output
  --since <period>      Time period (for git-activity)
  --help, -h            Show this help

Examples:
  claudia-report standup                    # Today's standup
  claudia-report standup --date 2026-02-03  # Specific date
  claudia-report daily --output report.md   # Save to file
  claudia-report standup --slack            # Slack format
  claudia-report git-activity --since "1 week ago"
  claudia-report summary

Price: $15 per report (customization available)
Contact: claudiaclawdbot@gmail.com
`);
}

// Main execution
function main() {
  const options = parseArgs();
  
  if (!options.type) {
    log.error('No report type specified');
    showHelp();
    process.exit(1);
  }
  
  if (!reports[options.type]) {
    log.error(`Unknown report type: ${options.type}`);
    log.info('Available types: standup, daily, git-activity, summary');
    process.exit(1);
  }
  
  log.info(`Generating ${options.type} report...`);
  
  let report;
  try {
    if (options.type === 'standup') {
      report = reports.standup(options.date, options);
    } else if (options.type === 'daily') {
      report = reports.daily(options.date, options);
    } else if (options.type === 'git-activity') {
      report = reports.gitActivity(options.since, options);
    } else if (options.type === 'summary') {
      report = reports.summary(options);
    }
  } catch (err) {
    log.error(`Failed to generate report: ${err.message}`);
    process.exit(1);
  }
  
  // Output
  if (options.output) {
    fs.writeFileSync(options.output, report);
    log.success(`Report saved to: ${options.output}`);
  } else {
    console.log('\n' + report);
  }
}

main();
