#!/usr/bin/env node

/**
 * README Generator CLI
 * Generates professional README.md files from project details
 * 
 * Usage: readme-gen "Project Name" "Description" --tech "Node.js,React"
 * 
 * Price: $15 (customization available)
 */

const fs = require('fs');
const path = require('path');

function generateREADME(name, description, tech = [], features = []) {
  const techBadges = tech.map(t => {
    const color = {
      'Node.js': 'green',
      'React': 'blue',
      'Python': 'yellow',
      'TypeScript': 'blue',
      'JavaScript': 'yellow',
      'Go': 'cyan',
      'Rust': 'orange'
    }[t] || 'blue';
    return `![${t}](https://img.shields.io/badge/${t.replace(/\s/g, '%20')}-${color})`;
  }).join(' ');

  const featuresList = features.length > 0 
    ? features.map(f => `- ${f}`).join('\n')
    : '- Core functionality\n- Easy to use\n- Well documented';

  return `# ${name}

${techBadges}

> ${description}

---

## ✨ Features

${featuresList}

---

## 🚀 Quick Start

### Installation

\`\`\`bash
npm install ${name.toLowerCase().replace(/\s/g, '-')}
# or
yarn add ${name.toLowerCase().replace(/\s/g, '-')}
\`\`\`

### Usage

\`\`\`javascript
// Add your usage example here
\`\`\`

---

## 📖 Documentation

### API Reference

#### \`functionName(param)\`

Description of what this function does.

**Parameters:**
- \`param\` (type) - Description

**Returns:**
- (type) - Description

---

## 🛠️ Development

### Setup

\`\`\`bash
git clone https://github.com/username/${name.toLowerCase().replace(/\s/g, '-')}.git
cd ${name.toLowerCase().replace(/\s/g, '-')}
npm install
\`\`\`

### Running Tests

\`\`\`bash
npm test
\`\`\`

### Building

\`\`\`bash
npm run build
\`\`\`

---

## 🤝 Contributing

Contributions are welcome! Please feel free to submit a Pull Request.

1. Fork the repository
2. Create your feature branch (\`git checkout -b feature/AmazingFeature\`)
3. Commit your changes (\`git commit -m 'Add some AmazingFeature'\`)
4. Push to the branch (\`git push origin feature/AmazingFeature\`)
5. Open a Pull Request

---

## 📄 License

This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.

---

## 🙏 Acknowledgments

- List any acknowledgments here
- Credits to contributors
- Inspiration sources

---

*Generated by Claudia's README Generator*  
*Need a custom README? Email: claudiaclawdbot@gmail.com*
`;
}

// CLI interface
const args = process.argv.slice(2);

if (args.length < 2) {
  console.log(`
📝 README Generator

Usage:
  readme-gen "Project Name" "Description" [options]

Options:
  --tech "tech1,tech2"     Comma-separated tech stack
  --features "feat1,feat2" Comma-separated features
  --output <file>          Output file (default: README.md)
  --help                   Show this help

Examples:
  readme-gen "My App" "A cool app" --tech "React,Node.js"
  readme-gen "CLI Tool" "Awesome CLI" --tech "TypeScript" --features "Fast,Easy,Powerful"

Price: $15 for custom README generation
Contact: claudiaclawdbot@gmail.com
`);
  process.exit(0);
}

const name = args[0];
const description = args[1];

let tech = [];
let features = [];
let output = 'README.md';

for (let i = 2; i < args.length; i++) {
  if (args[i] === '--tech' && args[i + 1]) {
    tech = args[i + 1].split(',').map(t => t.trim());
    i++;
  } else if (args[i] === '--features' && args[i + 1]) {
    features = args[i + 1].split(',').map(f => f.trim());
    i++;
  } else if (args[i] === '--output' && args[i + 1]) {
    output = args[i + 1];
    i++;
  }
}

const readme = generateREADME(name, description, tech, features);

fs.writeFileSync(output, readme);
console.log(`✅ Generated ${output} for "${name}"`);
console.log(`📧 Need customization? Email: claudiaclawdbot@gmail.com`);
