#!/bin/bash

# Daily Standup Reporter
# Generates a markdown report of daily development activity
# 
# Usage: ./standup-reporter.sh [date] [--slack]
# Price: $20 (customization available)
# Contact: claudiaclawdbot@gmail.com

set -e

DATE=${1:-$(date +%Y-%m-%d)}
SLACK_MODE=false

# Parse arguments
for arg in "$@"; do
  if [ "$arg" = "--slack" ]; then
    SLACK_MODE=true
  fi
done

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo ".")
cd "$REPO_ROOT"

# Generate report
REPORT="# 📊 Daily Standup Report - $DATE

## 📝 Summary
Generated: $(date '+%Y-%m-%d %H:%M:%S')
Repository: $(basename $(pwd))
Branch: $(git branch --show-current 2>/dev/null || echo 'N/A')

---

## 📈 Git Activity

### Commits
\`\`\`
$(git log --oneline --since="$DATE 00:00" --until="$DATE 23:59" 2>/dev/null || echo 'No commits today')
\`\`\`

**Total commits:** $(git rev-list --count HEAD --since="$DATE 00:00" --until="$DATE 23:59" 2>/dev/null || echo '0')

### Files Changed
\`\`\`
$(git diff --stat HEAD~$(git rev-list --count HEAD --since="$DATE 00:00" --until="$DATE 23:59" 2>/dev/null || echo 0)..HEAD 2>/dev/null || echo 'No changes')
\`\`\`

---

## ⏱️ Time Tracking

Focus time estimate: $(git log --since="$DATE 00:00" --until="$DATE 23:59" --pretty=format:"%H" 2>/dev/null | wc -l | xargs -I {} echo "{} hours (approx)")

---

## 🎯 Work Completed

### Features
- [ ] Feature implementation
- [ ] Bug fixes
- [ ] Documentation
- [ ] Testing

### Pull Requests
- [ ] PR created
- [ ] PR merged
- [ ] PR reviewed

### Issues
- [ ] Issues closed
- [ ] Issues opened

---

## 🚧 Blockers

*Document any blockers here*

---

## 📋 Tomorrow's Plan

*What are you working on next?*

---

*Generated by Claudia's Standup Reporter*  
*Need customization? Email: claudiaclawdbot@gmail.com*
"

# Output
if [ "$SLACK_MODE" = true ]; then
  # Slack-formatted output
  echo "$REPORT" | sed 's/^# /* /' | sed 's/^## /* /' | sed 's/^### /* /'
else
  # Standard markdown
  echo "$REPORT"
fi
